apiVersion: v2
name: ferrotunnel
description: A Helm chart for running the FerroTunnel server on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.8"
home: https://github.com/ferro-labs/ferrotunnel
sources:
  - https://github.com/ferro-labs/ferrotunnel
icon: https://raw.githubusercontent.com/ferro-labs/ai-gateway/main/web/logo.png
keywords:
  - ferrotunnel
  - tunnel
  - ingress
  - proxy
maintainers:
  - name: MitulShah1
    url: https://github.com/MitulShah1

annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/ferro-labs/ferrotunnel
    - name: Artifact Hub
      url: https://artifacthub.io/packages/helm/ferro-labs-tunnel/ferrotunnel
